# Javascript Node CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2
jobs:
  copay:
    docker:
      - image: circleci/node:8.12.0
      - image: circleci/mongo:4.1.2
        
    working_directory: ~/bws
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm ci 
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
      - run: npx codecov
      - store_artifacts:
          path: ./test
      - store_test_results:
          path: ./test

workflows:
  version: 2
  build_and_test:
    jobs:
      - copay
